train:
  _target_: src.datasets.MelDataset
  part: "train"
  shuffle_index: true
  segment_size: 8192
  melspec_params:
    sample_rate: 22050
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    pad: 384  # (n_fft - hop_length) // 2
    n_mels: 80
    center: false
    f_max: 8000
val:
  _target_: src.datasets.MelDataset
  part: "val"
  segment_size: 8192
  melspec_params: ${datasets.train.melspec_params}
test:
  _target_: src.datasets.MelDataset
  part: "test"
  segment_size: 131072
  melspec_params: ${datasets.train.melspec_params}
